users/urls.py
# -*- coding: utf-8 -*-

'''
@Time    : 2020/11/21 16:11
@Author  : Wanhao Zhang
@Contact : 1809721229@qq.com 
@FileName: urls.py
@Software: PyCharm
 
'''
# from django.conf.urls import url
# from django.contrib.auth.views import auth_login
#
# from . import views
#
# app_name='users'
# urlpatterns = [
#     # 登录页面
#     url(r'^login/$',auth_login, {'template_name': 'users/login.html'}, name='login'),
# ]
from django.conf.urls import url
from django.contrib.auth.views import LoginView
from . import views

app_name = 'users'

urlpatterns = [
    # 登录页面
    # url(r'^login/$', login, {'template_name': 'users/login.html'}, name = 'login'),
    url(r'^login/$', views.login, name="login"),
    url(r"^logout/$", views.logout, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^person_information/$', views.person_informarion, name='person_information'),
    url(r'^deleteUser/$', views.deleteUser, name="deleteUser"),
]

web_db/urls.py
from django.contrib import admin

from django.urls import include, path

urlpatterns = [
    # 主页
    path(r'', include('web_for_dbwork2.urls', namespace='web_for_dbwork2')),
    # path(r'users', include('users')),

    path(r'users/', include('users.urls', namespace='users')),
    path('admin/', admin.site.urls),
]

web_for_dbwork2/urls.py
# -*- coding: utf-8 -*-

'''
@Time    : 2020/11/9 23:32
@Author  : Wanhao Zhang
@Contact : 1809721229@qq.com 
@FileName: urls.py
@Software: PyCharm

'''
from django.urls import path

from web_for_dbwork2 import views

app_name = "web_for_dbwork2"

urlpatterns = [
    path('index/', views.index, name='index'),

    #  专业
    path('major_c2m/', views.major_c2m, name='major_c2m'),
    path('major_m2c/', views.major_m2c, name='major_m2c'),
    path('.major_recommend/', views.major_recommend, name='major_recommend'),
    # 学习
    path('study_main/', views.study_main, name='study_main'),
    path('study_router/', views.study_router, name='study_router'),
    # 生活
    path('life/', views.life, name='life'),


    # 专业推荐发帖
    path('add_major_recommend/', views.add_major_recommend, name='add_major_recommend'),

    # 生活发帖
    path('add_life_topic/', views.add_life_topic, name='add_life_topic'),

    # 学习路线发帖
    path('add_study_router/', views.add_study_router, name='add_study_router'),

    path('add_xing/', views.add_xing, name='add_xing'),
    path('add_grade/', views.add_grade, name='add_grade'),
    path('add_life/', views.add_life, name='add_life'),
    # 测试用
    path('page1/', views.page1, name='page1_name'),
    path('page2/', views.page2, name='page2_name'),

]

web_for_dbwork2/views.py
from django.contrib import messages
from django.shortcuts import render, redirect

# Create your views here.
from django.http import HttpResponse
import datetime

from users.models import All_Users
from web_db.base import check_login
from web_for_dbwork2.models import Course_Info, Course_Major, Major_In_System, Study_Field, Teacher_Course, \
    Teacher_Info, Resource_Web, Resource_Book, Recommend_Item_Major, Course_Sequence, Recommend_Item_Route, \
    Recommend_Item, Broadcast_Record, Favorite_Record, Grade_Num, Campus_Life

from django.template.defaulttags import register


@register.filter
def get_item(dictionary, key):
    return dictionary.get(key)


@check_login
def index(request):
    # is_login = request.session.get('is_login')
    # if is_login:
    #     return redirect('web_for_dbwork2:index')

    # 这里将来自数据库的的数据放到一个变量中，然后可以在html中显示
    test_list = ["张", "李"]
    context = {'test_list': test_list}
    return render(request, 'web_for_dbwork2/index.html', context)


# 专业
@check_login
def major_c2m(request):
    res = {}
    if request.method == "POST":
        search_course = request.POST.get("search_course")
        if search_course == "":
            return redirect("web_for_dbwork2:major_c2m")
        print(search_course)

        course_info = Course_Info.objects.filter(course_name=search_course).values("course_id")
        course_id = course_info[0]["course_id"]

        # 一门课程对应多个专业
        major_id_list = []
        course_major = Course_Major.objects.filter(course_id=course_id).values("major_id")
        for i in course_major:
            major_id_list.append(i["major_id"])

        major_name_list = []

        for i in major_id_list:
            major_in_sys = Major_In_System.objects.filter(major_id=i).values("major_name")
            major_name = major_in_sys[0]["major_name"]
            major_name_list.append(major_name)

        ############################################################################################################
        # 待定，研究方向需不需要

        # 专业id对应专业研究方向表  的  字典
        # dict_filed = {}
        field_list_list = []
        field_desc_list_list = []
        for i in major_id_list:
            study_filed_list = Study_Field.objects.filter(major_id=i)
            # dict_filed[i] = study_filed_list
            list = []
            list_desc = []
            for j in study_filed_list:
                list.append(j.study_field_name)
                list_desc.append(j.study_field_desc)
            field_list_list.append(list)
            field_desc_list_list.append(list_desc)

        # 研究方向 专业名-研究方向名
        field_dict = {}
        i = -1
        for name in major_name_list:
            i = i + 1
            field_dict[name] = field_list_list[i]

        # 给每个研究方向名对应一个研究描述，放进字典
        i = -1
        j = -1
        desc = {}
        for field_list in field_list_list:
            i = i + 1
            j = -1
            for field in field_list:
                j = j + 1
                desc[field] = field_desc_list_list[i][j]

        res = {'name_list': major_name_list, 'field_dict': field_dict, 'desc': desc, 'has_data': 1}

        return render(request, "web_for_dbwork2/major_c2m.html", res)

    return render(request, "web_for_dbwork2/major_c2m.html")


@check_login
def major_m2c(request):
    if request.method == "POST":

        res = {}

        search_major = request.POST.get("search_major")

        if search_major == "":
            return redirect("web_for_dbwork2:major_m2c")
        # 取major_id
        major_id = Major_In_System.objects.filter(major_name=search_major).values("major_id")[0]['major_id']

        # 取多个course_id
        course_id_list = []
        course_ids = Course_Major.objects.filter(major_id=major_id).values("course_id")
        for i in course_ids:
            course_id_list.append(i['course_id'])

        # 拿具体课程信息
        list = []
        for course_id in course_id_list:
            course_info = Course_Info.objects.filter(course_id=course_id)

            # 拿教师具体信息
            teacher_id_dict = Teacher_Course.objects.filter(course_id=course_id).values("teacher_id")
            teacher_info_list = []
            for i in teacher_id_dict:
                teacher_id = i["teacher_id"]
                teacher_info = Teacher_Info.objects.filter(teacher_id=teacher_id)

                teacher_info_list.append({'name': teacher_info[0].teacher_name,
                                          'age': teacher_info[0].teacher_age,
                                          'rank': teacher_info[0].teacher_rank})

            # 拿网页资源
            web_resource_list = []
            web_resource = Resource_Web.objects.filter(course_id=course_id)
            for i in web_resource:
                web_resource_list.append({'ISBN': i.resource_ISBN, 'name': i.resource_name})

            # 拿书籍资源
            book_resource_list = []
            book_resource = Resource_Book.objects.filter(course_id=course_id)
            for i in book_resource:
                book_resource_list.append({'ISBN': i.resource_ISBN, 'name': i.resource_name})

            list.append({'course_name': course_info[0].course_name,
                         'recommend_learn_grade': course_info[0].recommend_learn_grade,
                         'credits': course_info[0].credits,
                         'avg_grades': course_info[0].avg_grades,
                         'teacher_info_list': teacher_info_list,
                         'web_resource_list': web_resource_list,
                         'book_resource_list': book_resource_list})

        res['course_info'] = list

        res['major_name'] = search_major
        res['has_data'] = 1


        # 拿研究方向
        field_name = Study_Field.objects.filter(major_id=major_id)
        field = []
        for name in field_name:
            field.append(name.study_field_name)
        res['study_field'] = field

        return render(request, 'web_for_dbwork2/major_m2c.html', res)

    return render(request, 'web_for_dbwork2/major_m2c.html')


@check_login
def major_recommend(request):
    xinxi_1 = 1
    xinxi_2 = 7
    hang_1 = 8
    hang_2 = 12
    like_1 = 13
    like_2 = 16
    wenke_1 = 17
    wenke_2 = 21
    res = {}

    major_cate = {'xx': {}, 'hkht': {}, 'lk': {}, 'wk': {}}
    major_id_name = Major_In_System.objects.all()
    for i in range(1, wenke_2 + 1):
        if i <= xinxi_2:
            major_cate['xx'][str(i)] = major_id_name[i - 1].major_name
        elif hang_1 <= i <= hang_2:
            major_cate['hkht'][str(i)] = major_id_name[i - 1].major_name
        elif like_1 <= i <= like_2:
            major_cate['lk'][str(i)] = major_id_name[i - 1].major_name
        elif wenke_1 <= i <= wenke_2:
            major_cate['wk'][str(i)] = major_id_name[i - 1].major_name

    res['cate'] = major_cate
    if request.method == "POST":
        # 取到选择的id
        major_id = 1
        for major_id_choose in range(1, wenke_2 + 1):
            if_choose = request.POST.get(str(major_id_choose))
            major_id = int(major_id_choose)
            print(if_choose)
            if if_choose == "on":
                break

        # 拿到major_name
        major_name = Major_In_System.objects.filter(major_id=major_id).values("major_name")[0]["major_name"]

        # 通过major_name去拿专业推荐各种信息
        recommend_major_info = Recommend_Item_Major.objects.filter(major_name=major_name)
        info_list = []
        for one in recommend_major_info:
            title = one.major_title
            desc = one.major_desc
            rep1 = one.major_representive_course_1
            rep2 = one.major_representive_course_2
            rep3 = one.major_representive_course_3
            # 转换成名字
            rep1 = Course_Info.objects.filter(course_id=rep1)[0].course_name
            rep2 = Course_Info.objects.filter(course_id=rep2)[0].course_name
            rep3 = Course_Info.objects.filter(course_id=rep3)[0].course_name

            label1 = one.major_label_1
            label2 = one.major_label_2
            label3 = one.major_label_3
            like_num = one.like_num
            hot = one.hot
            watch = one.watch
            info_list.append({'title': title, 'desc': desc, 'rep1': rep1, 'rep2': rep2, 'rep3': rep3,
                              'label1': label1, 'label2': label2,
                              'label3': label3, 'like_num': like_num, 'hot': hot, 'watch': watch})

        res['recommend_info'] = info_list
        res['major_name'] = major_name
        print(major_name)

    return render(request, 'web_for_dbwork2/major_recommend.html', res)


# 学习
@check_login
def study_main(request):
    res = {'name': "hujinfei"}

    if request.method == "POST":
        search_course = request.POST.get("search_course")
        if search_course == "":
            return redirect("web_for_dbwork2:study_main")
        course_id = Course_Info.objects.filter(course_name=search_course)[0].course_id

        # 取多个route_id
        routes = Course_Sequence.objects.filter(course_id=course_id).values("route_id")
        route_list = []

        # 记录一下热度最大的下标
        maxHot = -1
        index = 0
        i = -1

        for one in routes:
            i = i + 1
            route_id = one["route_id"]
            rec_route = Recommend_Item_Route.objects.filter(item_route_id=route_id)
            route_name = rec_route[0].route_name
            item_id = rec_route[0].item_id
            like_num = rec_route[0].like_num
            hot = rec_route[0].hot
            if hot > maxHot:
                maxHot = hot
                index = i
            watch = rec_route[0].watch

            # 取user_id
            user_id = Recommend_Item.objects.filter(item_id=item_id)[0].user_id
            user_name = All_Users.objects.filter(user_id=user_id)[0].user_name

            route_list.append({'route_name': route_name, 'hot': hot, 'watch': watch, 'like_num': like_num,
                               'route_id': route_id, 'user_name': user_name})

        # 热度最大的提出来

web_for_dbwork2/templates/web_for_dbwork2/add_study_router.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>add_study_router</title>
</head>
<body>
{% extends "web_for_dbwork2/base.html" %}
{% block content %}

    <div class="container">
        <div class="jumbotron jumbotron-fluid">
          <div class="container">
             <h3>
                &nbsp;<a href="{% url 'web_for_dbwork2:study_main'  %}">学习路线</a>
              </h3>
              <form method="post" action={% url "web_for_dbwork2:add_study_router" %}>
                   {% csrf_token %}
                    <div class="form-group">
                        <div class="row">
                            <div class="col">
                                 <textarea class="form-control" rows="1" name="router_title" placeholder="请输入路线标题"></textarea>
                            </div>
                        </div>
                        <br>
                        路线详情：
                        &nbsp;<textarea class="form-control" rows="5" name="router_text" placeholder="请输入路线信息，课程名之间之间用-分割"></textarea>
                    </div>
                     &nbsp;<button type="submit" class="btn btn-outline-primary">发帖</button>
               </form>
          </div>
        </div>
    </div>

{% endblock %}
</body>
</html>

web_for_dbwork2/templates/web_for_dbwork2/base.html
{#{% load bootstrap3 %}#}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>base</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

   <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/4.3.1/css/bootstrap.min.css">
   <script src="https://cdn.staticfile.org/jquery/3.2.1/jquery.min.js"></script>
   <script src="https://cdn.staticfile.org/popper.js/1.15.0/umd/popper.min.js"></script>
   <script src="https://cdn.staticfile.org/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>

   <link rel="stylesheet" href="../../static/web_for_dbwork2/style.css">

    <link rel="stylesheet" type="text/css" href="../../static/web_for_dbwork2/arrow/dist/bootstrap-directional-buttons.css">
    <style type="text/css">
		#div1{
			width: 300px;
			height: 300px;
			{#border: #000 solid 1px;#}
			margin: 50px auto;
			overflow: hidden;
            text-align: center;
            line-height:300px;
            {#vertical-align: middle;#}
            {#text-align-all: center;#}
		}
		#div1 img{
			cursor: pointer;
			transition: all 0.6s;
		}
		#div1 img:hover{
			transform: scale(1.2);
		}


        /* Make the image fully responsive */
          .carousel-inner img {
              width: 100%;
              height: 100%;
          }

	</style>

</head>
<body>



<div class="container">

<div class="container-md">

<nav class="navbar navbar-expand-lg navbar-light bg-light">

  <a class="navbar-brand" href="{% url 'web_for_dbwork2:index' %}">航道首页</a>

<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link"  href="{% url 'web_for_dbwork2:study_main' %}">学习</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'web_for_dbwork2:life' %}">生活</a>
      </li>

    <!-- Dropdown -->
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
        专业
      </a>
      <div class="dropdown-menu">
          <a class="dropdown-item" href="{% url 'web_for_dbwork2:major_c2m' %}">课程2专业</a>
          <a class="dropdown-item" href="{% url 'web_for_dbwork2:major_m2c' %}">专业2课程</a>
          <a class="dropdown-item" href="{% url 'web_for_dbwork2:major_recommend' %}">专业推荐</a>
      </div>
    </li>


    </ul>
  <div class="form-inline my-2 my-lg-0">
      <ul class="navbar-nav mr-auto  my-2 my-lg-0">
                {% if request.COOKIES.IS_LOGIN %}
                  <li class="nav-item float-lg-right "><a class="nav-link" >Hello! {{ request.session.login_name }}</a></li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:person_information' %}">个人信息</a>
                    </li>
                  <li class="nav-item"><a class="nav-link" href="{% url 'users:logout' %}">退出</a></li>



                    <button type="button" class="btn " data-toggle="modal" data-target="#myModal">
              注销
            </button>

              <!-- 模态框 -->
              <div class="modal fade" id="myModal">
                <div class="modal-dialog modal-sm">
                  <div class="modal-content">

                    <!-- 模态框头部 -->
                    <div class="modal-header">
                      <h4 class="modal-title">确认注销</h4>
                      <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>

                    <!-- 模态框主体 -->
                    <div class="modal-body">
                      <div class="row">
                                    <form method="post" action={% url "users:deleteUser" %}>
                                        {% csrf_token %}
                                      <div class="form-row">
                                          <div class="col">
                                          <input type="text" class="form-control" name="name" placeholder="输入以 ‘BUAA’ 确认注销">
                                            </div>

                                        <div class="form-row">
                                            &nbsp;<button type="submit" class="btn btn-outline-dark">确认</button>
                                        </div>
                                      </div>
                                    </form>
                      </div>
                    </div>

                  </div>
                </div>
              </div>





                {% else %}
                      <li class="nav-item"><a class="nav-link" href="{% url 'users:register' %}">注册</a></li>
                      <li class="nav-item"><a class="nav-link"  href="{% url 'users:login' %}">登录</a></li>
              {% endif %}

      </ul>
  </div>

  </div>



</nav>
<br>

    <div class="page-header">
        {% block header %} {% endblock %}
    </div>
    <div>
        {% block content %}
        {% endblock%}
    </div>
</div>
</div>
<div style="height: 10px"></div>

<!-- Option 2: jQuery, Popper.js, and Bootstrap JS -->
    <script src="/web_for_dbwork2/static/web_for_dbwork2/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
{% comment %}为了模态的对话框{% endcomment %}
    <script>

        $(document).ready(function(){
            $('[data-toggle="popover"]').popover();
        });
    </script>
{% comment %}提示内容{% endcomment %}
    <script>
        $(document).ready(function(){
            $('[data-toggle="tooltip"]').tooltip();
        });
    </script>

{% comment %}测试{% endcomment %}
<script src="https://d3js.org/d3.v3.min.js"></script>

{% comment %}下面是life.html幻灯片自动翻页的脚本{% endcomment %}
<script>
 $('.carousel').carousel({
  interval: 5000
})
 </script>

{% comment %}使用qunee绘制线路图{% endcomment %}
<script src="http://demo.qunee.com/lib/qunee-min.js"></script>

{% comment %}研究方向网状图{% endcomment %}
<script>
    var graph = new Q.Graph("study_direction");

    function createNode(name, from){
        var node = graph.createNode(name);
        node.image = Q.Shapes.getShape(Q.Consts.SHAPE_CIRCLE, 40, 40);
        if(from){
            graph.createEdge(from, node);
        }
        return node;
    }
    var root = createNode("{{major_name}}");
    {% for field in study_field %}
        var node = createNode("{{ field }}", root);
    {% endfor %}

    var layouter = new Q.BalloonLayouter(graph);
    layouter.radiusMode = Q.Consts.RADIUS_MODE_UNIFORM;
    layouter.radius = 100;
    layouter.startAngle = Math.PI / 4;
    layouter.doLayout({callback: function(){
        graph.zoomToOverview();
    }});
</script>


<script>

    var graph = new Q.Graph("canvas");

    // 创建结点的函数
    function createNode(name, from){
        var node = graph.createNode(name);
        if(from){
            graph.createEdge(from, node);
        }
        return node;
    }

    // 根节点
    var root = createNode("Let's Start!", root);
    root.parentChildrenDirection = Q.Consts.DIRECTION_BOTTOM;

    {% for course in course_info_list %}
        var node = createNode("{{course.name}}", root);
        root = node;
        root.parentChildrenDirection = Q.Consts.DIRECTION_BOTTOM;

     {% endfor %}

     {#var node = createNode('2', root);#}
     {#   node.parentChildrenDirection = Q.Consts.DIRECTION_RIGHT;#}
     {#   node.layoutType = Q.Consts.LAYOUT_TYPE_EVEN_VERTICAL;#}
     {##}
     {#   var node1 = createNode('3', node);#}
     {#   node.parentChildrenDirection = Q.Consts.DIRECTION_RIGHT;#}
     {#   node.layoutType = Q.Consts.LAYOUT_TYPE_EVEN_VERTICAL;#}


    {#var i = 0;#}
    {#while(i++ < 2){#}
    {##}
    {#    switch (i) {#}
    {#        case 1: label = "C++ 书籍";#}
    {#                break;#}
    {#        case 2: label ="C++ 课程";#}
    {#                break;#}
    {#        default: label = "null";#}
    {#    }#}
    {#    // 创建子子节点#}
    {#    var node = createNode(label, root);#}
    {#    node.parentChildrenDirection = Q.Consts.DIRECTION_RIGHT;#}
    {#    node.layoutType = Q.Consts.LAYOUT_TYPE_EVEN_VERTICAL;#}
    {#    var j = 0;#}
    {#    while(j++ < 3){#}
    {##}
    {#        switch (i) {#}
    {#            case 1: label = "C++balabal";#}
    {#                    break;#}
    {#            case 2: label ="C++balaba";#}
    {#                    break;#}
    {#            default: label = "null";#}
    {#        }#}
    {#        createNode(label, node);#}
    {#    }#}


    // 画树状图
    var layouter = new Q.TreeLayouter(graph);
    layouter.layoutType = Q.Consts.LAYOUT_TYPE_EVEN_HORIZONTAL;
    layouter.doLayout({callback: function(){
        graph.zoomToOverview();
    }});
</script>





</body>
</html>

web_for_dbwork2/templates/web_for_dbwork2/index.html
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <title>index</title>
</head>

<body>

{#继承模板#}
{% extends "web_for_dbwork2/base.html" %}
{% load static %}
{#{% load bootstrap3 %}#}

{% block content %}

    <!--消息弹出-->
    {% include 'users/messageStyle.html' %}


<div class="container-md">

        <div class="jumbotron">
            <h3 class="display-4">欢迎来到——航亦有道</h3>
            <p class="lead">北航学生的学习生活推荐系统</p>
            <hr class="my-4">

            {% if request.session.is_authenticated %}
                <p>欢迎您{{request.session.login_name}}, 您可以从下面的板块中开始北航的生活学习探索</p>
            {% else %}
                <p>您尚未登录本系统，请先登录</p>
                <a class="btn btn-primary btn-lg" href="{% url 'users:login' %}" role="button">点此登录</a>
            {% endif %}

        </div>

        <div class="row">
            <div class="col-sm">
                <div class="container">
                    <div class="card" style="width: 18rem;">
                      <img src="../../static/web_for_dbwork2/images/yuhui.png" height="160" class="card-img-top" alt="美食">
                      <div class="card-body">
                        <h5 class="card-title">专业</h5>
                        <p class="card-text">这里有关于北航专业的一切信息，还有各路达人发布的热门帖子，快来探索你感兴趣的话题吧！</p>

                          <div class="dropdown">
                            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                              即刻探索
                            </button>
                            <div class="dropdown-menu">
                              <a class="dropdown-item" href="{% url 'web_for_dbwork2:major_c2m' %}">课程2专业</a>
                              <a class="dropdown-item" href="{% url 'web_for_dbwork2:major_m2c' %}">专业2课程</a>
                              <a class="dropdown-item" href="{% url 'web_for_dbwork2:major_recommend' %}">专业推荐</a>
                            </div>
                          </div>
                      </div>
                    </div>
                </div>
            </div>

            <div class="col-sm">
                 <div class="container">
                    <div class="card" style="width: 18rem;">
                      <img src="../../static/web_for_dbwork2/images/学习.png" height="160" class="card-img-top" alt="美食">
                      <div class="card-body">
                        <h5 class="card-title">学习</h5>
                        <p class="card-text">您可以输入想要学习的课程名称，查询该开设该课程的院系，以及该课程的详细信息</p>
                        <a href="{% url 'web_for_dbwork2:study_main' %}" class="btn btn-primary">即刻探索</a>
                      </div>
                    </div>
                </div>

            </div>

            <div class="col-sm">
                 <div class="container">
                    <div class="card" style="width: 18rem;">
                      <img src="../../static/web_for_dbwork2/images/生活.jpg" height="160" class="card-img-top" alt="美食">
                      <div class="card-body">
                          <h5 class="card-title">生活</h5>
                          <p class="card-text">在北航，你不仅能收获知识，更能感受大学生活的美好，十二道航味、航空博物馆...快来探索更多！</p>
                          <a href="{% url 'web_for_dbwork2:life' %}" class="btn btn-primary">即刻探索</a>
                      </div>
                    </div>
                </div>

            </div>
        </div>


    <div class="container">

    </div>


</div>

    <div>
        <hr color="gold">
        <center>
            <font color='black' size='2'>
            版权所有@hjf & fwt & zwh |地址：北京市海淀区学院路37号 |邮编：100019 |反馈意见：zhangwanhao@buaa.edu.cn
            </font>
        </center>
    </div>

{% endblock content %}


</body>
</html>

web_for_dbwork2/templates/web_for_dbwork2/major_main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>major_main</title>
</head>
<body>
{% extends "web_for_dbwork2/base.html" %}

{% block content %}

{% endblock content %}
</body>
</html>

web_for_dbwork2/templates/web_for_dbwork2/route_display.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>route_display</title>
</head>
<body>
{% extends 'web_for_dbwork2/base.html' %}
{% block content %}


{% endblock content %}
</body>
</html>

web_for_dbwork2/templates/web_for_dbwork2/study_router.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>study_rooter</title>
</head>
<body>
{% extends "web_for_dbwork2/base.html" %}

{% block content %}

    <div class="container">
        <div class="card bg-warning text-white">
         <div class="card-body text-center font-weight-bold">{{ route_name }}</div>
        </div>
        <br>

       {% comment %} <div style="height: 100px"></div>{% endcomment %}
    </div>

  <div style="height: 500px; width: 100%" id="canvas"></div>

{% endblock content %}
</body>
</html>