users/urls.py
# -*- coding: utf-8 -*-

'''
@Time    : 2020/11/21 16:11
@Author  : Wanhao Zhang
@Contact : 1809721229@qq.com 
@FileName: urls.py
@Software: PyCharm
 
'''
# from django.conf.urls import url
# from django.contrib.auth.views import auth_login
#
# from . import views
#
# app_name='users'
# urlpatterns = [
#     # 登录页面
#     url(r'^login/$',auth_login, {'template_name': 'users/login.html'}, name='login'),
# ]
from django.conf.urls import url
from django.contrib.auth.views import LoginView
from . import views

app_name = 'users'

urlpatterns = [
    # 登录页面
    # url(r'^login/$', login, {'template_name': 'users/login.html'}, name = 'login'),
    url(r'^login/$', views.login, name="login"),
    url(r"^logout/$", views.logout, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^person_information/$', views.person_informarion, name='person_information'),
    url(r'^deleteUser/$', views.deleteUser, name="deleteUser"),
]

web_db/urls.py
from django.contrib import admin

from django.urls import include, path

urlpatterns = [
    # 主页
    path(r'', include('web_for_dbwork2.urls', namespace='web_for_dbwork2')),
    # path(r'users', include('users')),

    path(r'users/', include('users.urls', namespace='users')),
    path('admin/', admin.site.urls),
]

web_for_dbwork2/urls.py
# -*- coding: utf-8 -*-

'''
@Time    : 2020/11/9 23:32
@Author  : Wanhao Zhang
@Contact : 1809721229@qq.com 
@FileName: urls.py
@Software: PyCharm

'''
from django.urls import path

from web_for_dbwork2 import views

app_name = "web_for_dbwork2"

urlpatterns = [
    path('index/', views.index, name='index'),

    #  专业
    path('major_c2m/', views.major_c2m, name='major_c2m'),
    path('major_m2c/', views.major_m2c, name='major_m2c'),
    path('.major_recommend/', views.major_recommend, name='major_recommend'),
    # 学习
    path('study_main/', views.study_main, name='study_main'),
    path('study_router/', views.study_router, name='study_router'),
    # 生活
    path('life/', views.life, name='life'),


    # 专业推荐发帖
    path('add_major_recommend/', views.add_major_recommend, name='add_major_recommend'),

    # 生活发帖
    path('add_life_topic/', views.add_life_topic, name='add_life_topic'),

    # 学习路线发帖
    path('add_study_router/', views.add_study_router, name='add_study_router'),

    path('add_xing/', views.add_xing, name='add_xing'),
    path('add_grade/', views.add_grade, name='add_grade'),
    path('add_life/', views.add_life, name='add_life'),
    # 测试用
    path('page1/', views.page1, name='page1_name'),
    path('page2/', views.page2, name='page2_name'),

]

users/models.py
from django.db import models


# Create your models here.

class All_Users(models.Model):
    user_id = models.AutoField(primary_key=True)
    user_name = models.CharField(max_length=20)
    user_email = models.EmailField()
    user_password = models.CharField(max_length=20)

    class Meta:
        db_table = "All_Users"

users/views.py
from django.contrib import messages
from django.shortcuts import render, redirect

from django.shortcuts import render
# Create your views here.
from django.contrib.auth import logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse

from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm

from users.models import All_Users
from web_db.base import check_login
from web_for_dbwork2.models import User_Info, Focus_Record, Broadcast_Record, Favorite_Record


def logout(request):
    # logout(request)
    # return HttpResponseRedirect(reverse('web_for_dbwork2:index'))
    request.COOKIES.clear()
    request.session.clear()
    response = redirect("users:login")
    response.set_cookie("IS_LOGIN", None)
    response.delete_cookie("IS_LOGIN")
    return response


def register(request):
    if request.method == "POST":
        """Register a new user."""
        register_name = request.POST.get("register_name")
        grade = request.POST.get("grade")
        major = request.POST.get("major")

        register_mail = request.POST.get("register_mail")
        register_password = request.POST.get("register_password")
        again_password = request.POST.get("again_password")
        if register_password != again_password:
            messages.error(request, "两次密码不一致，请重试")
            return HttpResponseRedirect(reverse('users:register'))
        # print(register_name, register_password, register_mail)
        user = All_Users(user_name=register_name, user_email=register_mail, user_password=register_password)
        user.save()

        id = All_Users.objects.last()
        ins = User_Info(user_id=id.user_id, user_grade=grade, user_major=major, user_grant=2)
        ins.save()

        # 重定向到登陆界面
        messages.success(request, "注册成功，恭喜您成为航亦有道大会员！")
        return redirect("users:login")
    """jump to html"""
    # url链接该视图，定向到注册页面
    return render(request, "users/register.html")


def login(request):
    if request.method == "POST":
        login_name = request.POST.get("login_name")
        login_password = request.POST.get("login_password")
        exist_name = All_Users.objects.filter(user_name=login_name)
        user = All_Users.objects.filter(user_name=login_name, user_password=login_password)

        # print(login_name, login_password)
        # print(len(user), len(exist_name))

        if len(user) >= 1:
            # 存下当前登陆进来的用户
            response = redirect(reverse("web_for_dbwork2:index"))
            response.set_cookie("user_id", user[0].user_id)
            response.set_cookie("user_name", user[0].user_name)
            response.set_cookie("user_email", user[0].user_email)
            # 标识用户已经登录，用于页面访问权限
            response.set_cookie("IS_LOGIN", True)
            # 用户名传出去
            request.session['login_name'] = login_name
            request.session['is_authenticated'] = True

            messages.success(request, "登陆成功，欢迎相约航亦有道！")

            return response

        elif len(exist_name) == 1 and len(user) == 0:
            messages.error(request, "粗心啦，密码不对噢")
            return redirect("users:login")
        else:
            messages.error(request, "找不到此用户呢，您可能没有注册噢")
            return redirect("users:login")

    return render(request, "users/login.html")


@check_login
def person_informarion(request):
    res = {}

    user_id = request.COOKIES.get("user_id")
    user_info = User_Info.objects.filter(user_id=user_id)
    grade = user_info[0].user_grade
    major = user_info[0].user_major
    res['grade'] = grade
    res['major'] = major
    res['name'] = request.COOKIES.get("user_name")

    # 取用户关注记录
    focus_info_list = Focus_Record.objects.filter(user_id=user_id).values("focus_id", "focus_time")

    focus_info = []

    for info in focus_info_list:
        name = All_Users.objects.filter(user_id=info['focus_id'])[0].user_name
        focus_info.append({'focus_name': name, 'focus_time': info['focus_time']})

    res['focus_info_list'] = focus_info

    # 取用户发布记录
    broadcast_list = []

    broadcast_record = Broadcast_Record.objects.filter(user_id=user_id)

    for record in broadcast_record:
        title = record.title
        time = record.broadcast_time
        broadcast_list.append({'broadcast_time': time, 'title': title})

    res['broadcast_list'] = broadcast_list

    # 取用户收藏记录
    # 学习路线
    study = []
    # 生活
    lives = []
    # 专业推荐帖子
    major = []

    favorite_info = Favorite_Record.objects.filter(user_id=user_id)
    for info in favorite_info:
        title = info.favorite_title
        owner_name = info.owner_name
        time = info.favorite_time
        contentAndId = info.favorite_content_id
        if contentAndId[0:5] == "study":
            study.append({'title': title, 'owner_name': owner_name, 'time': time})
            pass
        elif contentAndId[0:5] == "lives":
            lives.append({'title': title, 'owner_name': owner_name, 'time': time})
            pass
        elif contentAndId[0:5] == "major":
            major.append({'title': title, 'owner_name': owner_name, 'time': time})
            pass
        else:
            pass

    res['fav_study'] = study
    res['fav_lives'] = lives
    res['fav_major'] = major

    return render(request, 'users/person_information.html', res)


def deleteUser(request):
    user_id = request.COOKIES["user_id"]
    All_Users.objects.filter(user_id=user_id).delete()
    User_Info.objects.filter(user_id=user_id).delete()
    request.COOKIES.clear()
    request.session.clear()
    response = redirect("users:login")
    response.set_cookie("IS_LOGIN", None)
    response.delete_cookie("IS_LOGIN")
    return response

users/templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>login</title>
</head>
<body>
{% extends 'web_for_dbwork2/base.html' %}
{% load bootstrap3 %}

{% block header %}

{% endblock %}

{% block content %}

    <div class="container-md">
    <!--消息弹出-->
    {% include 'users/messageStyle.html' %}

       <form method="post" action={% url 'users:login' %}>
           {% csrf_token %}
           <div class="form-group row" >
              <div class="col">
                  <label for="user">用户名:</label>
                  <input type="text" class="form-control w-25" name="login_name" placeholder="请输入账号">
              </div>
          </div>
          <div class="form-group row">
              <div class="col">
                <label for="pwd">密码:</label>
                <input type="password" class="form-control w-25" name="login_password" placeholder="请输入密码">
              </div>
          </div>
          <div class="form-check row">
            <label class="form-check-label">
             &nbsp&nbsp&nbsp <input class="form-check-input" type="checkbox"> Remember me
            </label>
          </div>
           <br>
          <button type="submit" class="btn btn-primary">登录</button>
        </form>

    </div>
{% endblock content %}

</body>
</html>

users/templates/users/messageStyle.html
{% if messages %}
    {% for message in messages %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
            <div class="alert alert-info alert-dismissable">
                <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                【信息】：{{ message }}
            </div>
        {% endif %}

        {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
            <div class="alert alert-success alert-dismissable">
                <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                【成功】：{{ message }}
            </div>
        {% endif %}

        {% if message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
            <div class="alert alert-warning alert-dismissable">
                <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                【警告】：{{ message }}
            </div>
        {% endif %}

        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
            <div class="alert alert-danger alert-dismissable">
                <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                【错误】：{{ message }}
            </div>
        {% endif %}
    {% endfor %}
{% endif %}

users/templates/users/person_information.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>person_information</title>
</head>
<body>
{% extends 'web_for_dbwork2/base.html' %}
{% block header %}

{% endblock %}

{% block content %}

    <!--消息弹出-->
    {% include 'users/messageStyle.html' %}


    <div class="container">
    <div class="row">
        <div class="col">
            <div class="card" style="width:400px">
    <img class="card-img-top" src="https://static.runoob.com/images/mix/img_avatar.png" alt="Card image" style="width:100%">
    <div class="card-body">
      <h4 class="card-title">{{name}}</h4>
      <p class="card-text">在读年级：{{ grade }}</p>
        <p class="card-text">在读专业：{{ major }}</p>
    </div>
  </div>
        </div>

        <div class="col">
                <div id="accordion">
    <div class="card">
      <div class="card-header">
        <a class="card-link" data-toggle="collapse" href="#collapseOne">
          我的关注
        </a>
      </div>
      <div id="collapseOne" class="collapse show" >
        <div class="card-body">
            {% for info in focus_info_list %}
          <li>
              {{info.focus_name}}，关注时间：{{ info.focus_time }}
          </li>
            {% endfor %}

        </div>
      </div>
    </div>
    <div class="card">
      <div class="card-header">
        <a class="collapsed card-link" data-toggle="collapse" href="#collapseTwo">
        我的收藏
      </a>
      </div>
      <div id="collapseTwo" class="collapse" >
        <div class="card-body">
            {% if fav_study.count != 0  %}

                <h5 class="card-title"><kbd color="blue">学习路线</kbd></h5>
                {% for fav in fav_study %}
                    <li>
                        {{ fav.title }}.{{ fav.owner_name }}，收藏时间：{{ fav.time }}
                    </li>
                {% endfor %}
            {% endif %}

            <br>

            {% if fav_lives.count != 0  %}
                 <h5 class="card-title"><kbd color="blue">生活</kbd></h5>
                {% for fav in fav_lives %}
                    <li>
                        {{ fav.title }}.{{ fav.owner_name }}，收藏时间：{{ fav.time }}
                    </li>
                {% endfor %}
            {% endif %}

            <br>

            {% if fav_major.count != 0  %}
                 <h5 class="card-title"><kbd color="blue">专业推荐</kbd></h5>
                {% for fav in fav_major %}
                    <li>
                        {{ fav.title }}.{{ fav.owner_name }}，收藏时间：{{ fav.time }}
                    </li>
                {% endfor %}
            {% endif %}

            <br>

{#            <li>#}
{#                <a href="{% url 'web_for_dbwork2:study_router' %}">Cpp学习路线跳转模板</a>#}
{#            </li>#}

        </div>
      </div>
    </div>
    <div class="card">
      <div class="card-header">
        <a class="collapsed card-link" data-toggle="collapse" href="#collapseThree">
          我的发布
        </a>
      </div>
      <div id="collapseThree" class="collapse" >
        <div class="card-body">
            {% for broadcast in broadcast_list %}
                <li>
                {{ broadcast.title }}，发布时间：{{ broadcast.broadcast_time }}
                </li>
            {% endfor %}
{#            <li>#}
{#                 <a href="{% url 'web_for_dbwork2:study_router' %}">Cpp学习路线跳转模板</a>#}
{#            </li>#}

        </div>
      </div>
    </div>

{#                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">#}
{#              注销#}
{#            </button>#}
{##}
{#              <!-- 模态框 -->#}
{#              <div class="modal fade" id="myModal">#}
{#                <div class="modal-dialog modal-sm">#}
{#                  <div class="modal-content">#}
{##}
{#                    <!-- 模态框头部 -->#}
{#                    <div class="modal-header">#}
{#                      <h4 class="modal-title">确认注销</h4>#}
{#                      <button type="button" class="close" data-dismiss="modal">&times;</button>#}
{#                    </div>#}
{##}
{#                    <!-- 模态框主体 -->#}
{#                    <div class="modal-body">#}
{#                      <div class="row">#}
{#                                    <form method="post" action={% url "users:deleteUser" %}>#}
{#                                        {% csrf_token %}#}
{#                                      <div class="form-row">#}
{#                                          <div class="col">#}
{#                                          <input type="text" class="form-control" name="name" placeholder="输入以 ‘BUAA’ 确认注销">#}
{#                                            </div>#}
{##}
{#                                        <div class="form-row">#}
{#                                            &nbsp;<button type="submit" class="btn btn-outline-dark">确认</button>#}
{#                                        </div>#}
{#                                      </div>#}
{#                                    </form>#}
{#                      </div>#}
{#                    </div>#}
{##}
{#                  </div>#}
{#                </div>#}
{#              </div>#}

  </div>
        </div>

    </div>

</div>

{% endblock %}
</body>
</html>

users/templates/users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>register</title>
</head>
<body>
{% extends "web_for_dbwork2/base.html" %}

{% block content %}
     <!--消息弹出-->
    {% include 'users/messageStyle.html' %}
   <div class="container-md">
       <form method="post" action={% url 'users:register' %}>
           {% csrf_token %}
          <div class="form-group row" >
              <div class="col-sm">
                  <label for="user">账户名:</label>
                  <input type="text" class="form-control w-25" name="register_name" placeholder="请输入账号">
              </div>
          </div>
           <div class="form-group row" >
              <div class="col">
                  <label for="email">邮箱:</label>
                  <input type="email" class="form-control w-25" name="register_mail" placeholder="请输入邮箱">
              </div>
          </div>

           <div class="form-group row" >
              <div class="col">
                  <label for="email">年级:</label>
                  <input type="text" class="form-control w-25" name="grade" placeholder="请输入年级">
              </div>
          </div>

           <div class="form-group row" >
              <div class="col">
                  <label for="email">专业:</label>
                  <input type="text" class="form-control w-25" name="major" placeholder="请输入专业">
              </div>
          </div>



          <div class="form-group row">
              <div class="col">
                <label for="pwd">密码:</label>
                <input type="password" class="form-control w-25" name="register_password" placeholder="请输入密码">
              </div>
          </div>

           <div class="form-group row">
              <div class="col">
                <label for="pwd">请确认密码:</label>
                <input type="password" class="form-control w-25" name="again_password" placeholder="请再次输入密码">
              </div>
          </div>

           <br>
          <button type="submit" class="btn btn-primary">注册</button>
        </form>

   </div>

{% comment %}
  <form method="post" action="{% url 'users:register' %}" class="form">
    {% csrf_token %}
{#      怎么修改？？#}
        {{ form.as_p }}

    <button name="submit" class="btn btn-primary">注册</button>
    <input type="hidden" name="next" value="{% url 'web_for_dbwork2:index' %}" />

  </form>
{% endcomment %}

{% endblock content %}

</body>
</html>